#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linters and formatters on staged files
npx lint-staged

# Run a full typecheck before commit
npm run typecheck

# Generate documentation before commit
npm run docs